#!/usr/bin/env node
/**
 * Token build. Reads design-tokens.json (the single source of truth), resolves every
 * {alias} including the dark override map, and emits src/styles/theme.css as one
 * CSS-variable layer: :root plus :root[data-theme="dark"].
 *
 * Self-contained on purpose: this repo has to build on a server that does not have
 * the design-system kit checked out.
 *
 *   node scripts/build-theme.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = resolve(ROOT, 'design-tokens.json');
const OUT = resolve(ROOT, 'src/styles/theme.css');

const tokens = JSON.parse(readFileSync(SRC, 'utf8'));

const at = (root, path) =>
  path.split('.').reduce((o, k) => (o && typeof o === 'object' ? o[k] : undefined), root);

/** Flatten the dark override map to { 'surface.page': '#...' } */
function flattenDark(node, prefix = '', acc = {}) {
  for (const [k, v] of Object.entries(node || {})) {
    if (k.startsWith('$')) continue;
    if (v && typeof v === 'object' && '$value' in v) acc[`${prefix}${k}`] = v.$value;
    else if (v && typeof v === 'object') flattenDark(v, `${prefix}${k}.`, acc);
  }
  return acc;
}
const DARK = flattenDark(tokens.dark);

/** Follow {alias} chains to a literal. In dark mode a semantic.* hop re-enters the override map. */
function resolveValue(value, dark, depth = 0) {
  if (depth > 12) throw new Error(`alias cycle at ${value}`);
  if (typeof value !== 'string') return value;
  if (!(value.startsWith('{') && value.endsWith('}'))) {
    // a shadow can embed {refs} inside a longer string
    return value.replace(/\{([^}]+)\}/g, (m, ref) => {
      const r = resolveValue(`{${ref}}`, dark, depth + 1);
      return typeof r === 'string' || typeof r === 'number' ? String(r) : m;
    });
  }
  let ref = value.slice(1, -1).trim().replace(/^(\.\.\/|\.\/)+/, '');
  if (dark && ref.startsWith('semantic.')) {
    const key = ref.slice('semantic.'.length);
    if (key in DARK) return resolveValue(DARK[key], dark, depth + 1);
  }
  const node = at(tokens, ref);
  if (!node || typeof node !== 'object' || !('$value' in node)) {
    throw new Error(`unresolved token reference: {${ref}}`);
  }
  return resolveValue(node.$value, dark, depth + 1);
}

function cssValue(v, dark) {
  const out = resolveValue(v, dark);
  if (Array.isArray(out)) return `cubic-bezier(${out.join(', ')})`;
  return String(out);
}

/** [token path, css var prefix] */
const GROUPS = [
  ['semantic', 'color-'],
  ['component', 'color-'],
  ['font.family', 'font-'],
  ['font.size', 'text-'],
  ['font.weight', 'weight-'],
  ['font.leading', 'leading-'],
  ['font.tracking', 'tracking-'],
  ['font.measure', 'measure-'],
  ['space', 'space-'],
  ['radius', 'radius-'],
  ['stroke', 'stroke-'],
  ['shadow', 'shadow-'],
  ['motion.duration', 'duration-'],
  ['motion.easing', 'ease-'],
  ['breakpoint', 'bp-'],
  ['container', 'container-'],
  ['z', 'z-'],
];

// Colour and shadow vars are re-emitted for dark; the static scales are not.
const THEMED = new Set(['semantic', 'component', 'shadow']);

/**
 * `path` is the token's own dotted path inside its group. For the semantic tier that
 * path IS the key of the dark override map, so a dark build has to consult the map on
 * the token itself, not only on the {semantic.*} aliases that point at it.
 */
function emit(node, prefix, out, dark, path = '') {
  for (const [k, v] of Object.entries(node || {})) {
    if (k.startsWith('$')) continue;
    const here = path ? `${path}.${k}` : k;
    if (v && typeof v === 'object' && '$value' in v) {
      const raw = dark && here in dark ? dark[here] : v.$value;
      out.push(`  --${prefix}${k}: ${cssValue(raw, dark)};`);
    } else if (v && typeof v === 'object') {
      emit(v, `${prefix}${k}-`, out, dark, here);
    }
  }
}

const light = [];
const dark = [];
for (const [path, prefix] of GROUPS) {
  const node = at(tokens, path);
  if (!node) throw new Error(`missing token group: ${path}`);
  emit(node, prefix, light, null);
  if (THEMED.has(path.split('.')[0])) emit(node, prefix, dark, DARK);
}

const uniq = (a) => [...new Map(a.map((l) => [l.split(':')[0], l])).values()];
const lightVars = uniq(light);
const darkVars = uniq(dark).filter((l) => !lightVars.includes(l));

const css = `/* Generated by scripts/build-theme.mjs from design-tokens.json. Do not edit by hand. */
:root {
  color-scheme: light dark;
${lightVars.join('\n')}
}

:root[data-theme="dark"] {
${darkVars.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${darkVars.map((l) => '  ' + l).join('\n')}
  }
}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, css);
console.log(`theme.css: ${lightVars.length} light vars, ${darkVars.length} dark overrides -> ${OUT.replace(ROOT + '/', '')}`);
